import React,{useEffect,useState} from 'react';
import {supabase} from './supabaseClient';

const CATEGORIES=['Bổ sung trang thiết bị','Dụng cụ tập luyện','Bảo trì','Bảo dưỡng','Sửa chữa CLB'];
const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const date=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('vi-VN'):'—';
const today=()=>new Date().toISOString().slice(0,10);
const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const moveDate=(d,days)=>{const x=new Date(d);x.setDate(x.getDate()+days);return x};
const PERIOD_GROUPS=[
 {title:'Theo ngày',items:[['today','Hôm nay'],['yesterday','Hôm qua']]},
 {title:'Theo tuần',items:[['this_week','Tuần này'],['last_week','Tuần trước'],['last_7_days','7 ngày qua']]},
 {title:'Theo tháng',items:[['this_month','Tháng này'],['last_month','Tháng trước']]},
 {title:'Theo quý',items:[['this_quarter','Quý này'],['last_quarter','Quý trước']]},
 {title:'Theo năm',items:[['this_year','Năm nay'],['last_year','Năm trước']]}
];
const PERIOD_LABELS=Object.fromEntries(PERIOD_GROUPS.flatMap(g=>g.items));
function presetRange(kind){
 const n=new Date();n.setHours(12,0,0,0);let start=new Date(n),end=new Date(n);
 if(kind==='yesterday'){start=moveDate(n,-1);end=new Date(start)}
 if(kind==='this_week'){start=moveDate(n,-((n.getDay()+6)%7))}
 if(kind==='last_week'){end=moveDate(n,-((n.getDay()+6)%7)-1);start=moveDate(end,-6)}
 if(kind==='last_7_days')start=moveDate(n,-6);
 if(kind==='this_month')start=new Date(n.getFullYear(),n.getMonth(),1,12);
 if(kind==='last_month'){start=new Date(n.getFullYear(),n.getMonth()-1,1,12);end=new Date(n.getFullYear(),n.getMonth(),0,12)}
 if(kind==='this_quarter')start=new Date(n.getFullYear(),Math.floor(n.getMonth()/3)*3,1,12);
 if(kind==='last_quarter'){const q=Math.floor(n.getMonth()/3)*3;start=new Date(n.getFullYear(),q-3,1,12);end=new Date(n.getFullYear(),q,0,12)}
 if(kind==='this_year')start=new Date(n.getFullYear(),0,1,12);
 if(kind==='last_year'){start=new Date(n.getFullYear()-1,0,1,12);end=new Date(n.getFullYear()-1,11,31,12)}
 return[isoDate(start),isoDate(end)];
}
const branchName=(branches,id)=>branches.find(b=>b.id===id)?.name||'—';
const message=e=>alert(e?.message||String(e));
const actionButtons=(row,decide)=>row.status==='Chờ duyệt'?<div className='ops-actions'><span className='request-status st-0'>Chờ duyệt</span><div><button type='button' className='primary' onClick={()=>decide(row,'Đã duyệt')}>Duyệt</button><button type='button' className='danger' onClick={()=>decide(row,'Từ chối')}>Từ chối</button></div></div>:<span className='request-status st-1'>{row.status}</span>;

export function RequestsPage({profile,branches}){
 const manager=['admin','manager'].includes(profile.role);
 const [form,setForm]=useState({request_type:CATEGORIES[0],branch_id:profile.branch_id||'',title:'',description:'',amount:'',date_from:''});
 const [filter,setFilter]=useState({branch_id:'',request_type:'',from:'',to:''});
 const [rows,setRows]=useState([]),[summary,setSummary]=useState({count:0,amount:0,approved:0}),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);let q=supabase.from('internal_requests').select('id,request_type,title,description,amount,date_from,branch_id,status,created_at,decision_note').in('request_type',CATEGORIES).order('created_at',{ascending:false}).limit(100);
 if(filter.branch_id)q=q.eq('branch_id',filter.branch_id);if(filter.request_type)q=q.eq('request_type',filter.request_type);if(filter.from)q=q.gte('created_at',filter.from+'T00:00:00');if(filter.to)q=q.lte('created_at',filter.to+'T23:59:59');
 const [list,total]=await Promise.all([q,manager?supabase.rpc('get_proposal_summary',{target_branch:filter.branch_id||null,target_category:filter.request_type||null,start_on:filter.from||null,end_on:filter.to||null}):Promise.resolve({data:null})]);
 if(list.error)message(list.error);else setRows(list.data||[]);if(total.error)message(total.error);else setSummary(total.data||{count:0,amount:0,approved:0});setLoading(false)}
 useEffect(()=>{load()},[profile.id,filter.branch_id,filter.request_type,filter.from,filter.to]);
 async function submit(e){e.preventDefault();if(busy)return;if(!form.branch_id||!form.date_from)return message('Chọn cơ sở và ngày dự kiến thực hiện.');setBusy(true);const {error}=await supabase.from('internal_requests').insert({request_type:form.request_type,branch_id:form.branch_id,title:form.title.trim(),description:form.description.trim(),amount:Number(form.amount),date_from:form.date_from,created_by:profile.id});setBusy(false);if(error)return message(error);setForm(f=>({...f,title:'',description:'',amount:''}));load()}
 async function decide(row,status){const note=status==='Từ chối'?prompt('Lý do từ chối:'):'';if(status==='Từ chối'&&!note?.trim())return;const {error}=await supabase.rpc('decide_internal_request',{request_id:row.id,new_status:status,note:note||''});if(error)message(error);else load()}
 return <div className='ops-stack'><section className='panel'><h3>Đề xuất cơ sở vật chất</h3><form className='ops-fields' onSubmit={submit}><label>Cơ sở<select required value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value=''>Chọn cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Hạng mục<select value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value})}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Nội dung<input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Chi tiết<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Chi phí dự kiến<input type='number' required min='0' step='1000' value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Ngày dự kiến thực hiện<input required type='date' value={form.date_from} onChange={e=>setForm({...form,date_from:e.target.value})}/></label><button className='primary' disabled={busy}>{busy?'Đang gửi...':'Gửi đề xuất'}</button></form></section>
 {manager&&<section className='panel'><h3>Theo dõi đề xuất</h3><div className='ops-fields'><label>Cơ sở<select value={filter.branch_id} onChange={e=>setFilter({...filter,branch_id:e.target.value})}><option value=''>Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Hạng mục<select value={filter.request_type} onChange={e=>setFilter({...filter,request_type:e.target.value})}><option value=''>Tất cả hạng mục</option>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Từ ngày gửi<input type='date' value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>Đến ngày gửi<input type='date' value={filter.to} onChange={e=>setFilter({...filter,to:e.target.value})}/></label></div><div className='ops-summary'><span>Số đề xuất: <b>{summary.count||0}</b></span><span>Chi phí đề xuất: <b>{money(summary.amount)}</b></span><span>Đã duyệt: <b>{summary.approved||0}</b></span></div></section>}
 <section className='panel'><h3>Danh sách đề xuất</h3>{loading?<p>Đang tải...</p>:<div className='ops-table'><table><thead><tr><th>Đề xuất / Cơ sở</th><th>Thời gian</th><th>Chi phí</th><th>Trạng thái / Xử lý</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.request_type}</b><strong>{branchName(branches,r.branch_id)}</strong><span>{r.title} · {r.description}</span></td><td>Gửi: {date(r.created_at)}<br/>Dự kiến: {date(r.date_from)}</td><td>{money(r.amount)}</td><td>{manager?actionButtons(r,decide):r.status}</td></tr>)}{!rows.length&&<tr><td colSpan='4'>Chưa có đề xuất.</td></tr>}</tbody></table></div>}</section></div>
}

export function LeavePage({profile,branches,users}){
 const manager=['admin','manager'].includes(profile.role);
 const [form,setForm]=useState({employee_id:profile.id,start_date:today(),end_date:today(),reason:''});
 const [filter,setFilter]=useState({branch_id:'',employee_id:'',balance:''});
 const [staff,setStaff]=useState([]),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const [kiotPreview,setKiotPreview]=useState(null),[syncingId,setSyncingId]=useState('');
 const visibleUsers=manager?users.filter(u=>u.active&&u.role!=='pending'):users.filter(u=>u.id===profile.id);
 async function load(){setLoading(true);let q=supabase.from('leave_balances').select('employee_id,branch_id,hire_date,accrued,used,reserved,remaining').limit(300);let rq=supabase.from('leave_requests').select('id,employee_id,branch_id,start_date,end_date,paid_days,unpaid_days,reason,status').eq('status','Chờ duyệt').order('created_at',{ascending:false}).limit(100);
 if(filter.branch_id){q=q.eq('branch_id',filter.branch_id);rq=rq.eq('branch_id',filter.branch_id)}if(filter.employee_id){q=q.eq('employee_id',filter.employee_id);rq=rq.eq('employee_id',filter.employee_id)}
 const [a,b]=await Promise.all([q,rq]);if(a.error)message(a.error);else setStaff((a.data||[]).filter(x=>!filter.balance||filter.balance==='empty'&&x.remaining<=0||filter.balance==='available'&&x.remaining>0));if(b.error)message(b.error);else setRows(b.data||[]);setLoading(false)}
 useEffect(()=>{load()},[profile.id,filter.branch_id,filter.employee_id,filter.balance]);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);const {error}=await supabase.rpc('submit_leave_request',{target_employee:form.employee_id,start_on:form.start_date,end_on:form.end_date,leave_reason:form.reason.trim()});setBusy(false);if(error)message(error);else{setForm(f=>({...f,reason:''}));load()}}
 async function decide(row,status){const note=status==='Từ chối'?prompt('Lý do từ chối:'):'';if(status==='Từ chối'&&!note?.trim())return;const {error}=await supabase.rpc('decide_leave_request',{request_id:row.id,new_status:status,note:note||''});if(error)message(error);else load()}
 async function previewKiot(row){
  if(syncingId)return;setSyncingId(row.id);
  try{
   const {data:{session}}=await supabase.auth.getSession();
   const response=await fetch('/api/leave/kiot-sync-test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({leave_request_id:row.id})});
   const result=await response.json();
   if(!response.ok||!result.success)throw new Error(result.error||'Không tạo được bản mô phỏng Kiot.');
   setKiotPreview(result);
  }catch(error){message(error)}finally{setSyncingId('')}
 }
 async function setHireDate(row){const value=prompt('Ngày bắt đầu làm việc (YYYY-MM-DD):',row.hire_date||'');if(!value)return;const {error}=await supabase.rpc('set_leave_hire_date',{target_employee:row.employee_id,start_on:value});if(error)message(error);else load()}
 const userName=id=>users.find(u=>u.id===id)?.full_name||'Nhân sự';
 return <div className='ops-stack'><section className='panel'><h3>Theo dõi nghỉ phép nhân sự</h3><form className='ops-fields' onSubmit={submit}><label>Nhân sự<select value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}>{visibleUsers.map(u=><option key={u.id} value={u.id}>{u.full_name} · {u.role}</option>)}</select></label><label>Từ ngày<input required type='date' value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>Đến ngày<input required type='date' min={form.start_date} value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><label>Lý do nghỉ<input required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className='primary' disabled={busy||!visibleUsers.length}>{busy?'Đang gửi...':'Gửi đơn nghỉ'}</button></form></section>
 <section className='panel'><h3>Đơn nghỉ phép chờ duyệt</h3><div className='ops-table'><table><thead><tr><th>Nhân sự & lý do</th><th>Thời gian nghỉ</th><th>Hình thức</th><th>Trạng thái / Xử lý</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{userName(r.employee_id)}</b><span>{branchName(branches,r.branch_id)}<br/>{r.reason}</span></td><td>{date(r.start_date)} – {date(r.end_date)}</td><td>{r.paid_days} ngày có lương<br/><span className='metric-danger'>{r.unpaid_days} ngày không lương{r.unpaid_days>0?' (hết phép)':''}</span></td><td>{manager?<div className='ops-actions leave-review-actions'><span className='request-status st-0'>Chờ duyệt</span><div><button type='button' className='primary' onClick={()=>decide(r,'Đã duyệt')}>Duyệt</button><button type='button' className='danger' onClick={()=>decide(r,'Từ chối')}>Từ chối</button><button type='button' className='kiot-test-btn' disabled={syncingId===r.id} onClick={()=>previewKiot(r)}>{syncingId===r.id?'Đang kiểm tra...':'Test Kiot'}</button></div></div>:<span className='request-status st-0'>Chờ duyệt</span>}</td></tr>)}{!rows.length&&<tr><td colSpan='4'>Không có đơn chờ duyệt.</td></tr>}</tbody></table></div></section>
 {manager&&<section className='panel'><h3>Lọc nhân sự</h3><div className='ops-fields'><label>Cơ sở<select value={filter.branch_id} onChange={e=>setFilter({...filter,branch_id:e.target.value,employee_id:''})}><option value=''>Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Nhân sự<select value={filter.employee_id} onChange={e=>setFilter({...filter,employee_id:e.target.value})}><option value=''>Tất cả nhân sự</option>{visibleUsers.filter(u=>!filter.branch_id||u.branch_id===filter.branch_id).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label><label>Ngày phép<select value={filter.balance} onChange={e=>setFilter({...filter,balance:e.target.value})}><option value=''>Tất cả</option><option value='available'>Còn phép</option><option value='empty'>Hết phép</option></select></label></div></section>}
 <section className='panel'><h3>Ngày phép từng nhân sự</h3>{loading?<p>Đang tải...</p>:<div className='ops-table'><table><thead><tr><th>Nhân sự / Cơ sở</th><th>Tích lũy</th><th>Đã dùng</th><th>Chờ duyệt</th><th>Còn phép</th>{profile.role==='admin'&&<th>Ngày vào làm</th>}</tr></thead><tbody>{staff.map(r=><tr key={r.employee_id}><td><b>{userName(r.employee_id)}</b><span>{branchName(branches,r.branch_id)}</span></td><td>{r.hire_date?r.accrued+'/12':'Chưa thiết lập'}</td><td>{r.used}</td><td>{r.reserved}</td><td><b>{r.remaining}</b></td>{profile.role==='admin'&&<td><button type='button' onClick={()=>setHireDate(r)}>{r.hire_date?date(r.hire_date):'Thiết lập'}</button></td>}</tr>)}{!staff.length&&<tr><td colSpan='6'>Chưa có nhân sự phù hợp.</td></tr>}</tbody></table></div>}</section>
 {kiotPreview&&<div className='modal' onMouseDown={()=>setKiotPreview(null)}><section className='modal-card kiot-preview-modal' onMouseDown={e=>e.stopPropagation()}><div className='modal-head'><div><h3>Mô phỏng đồng bộ Kiot</h3><p className='test-mode-badge'>CHẾ ĐỘ TEST · KHÔNG GHI KIOT</p></div><button type='button' onClick={()=>setKiotPreview(null)}>×</button></div><div className='kiot-preview-summary'><div><span>Nhân sự</span><b>{kiotPreview.employee?.name}</b><small className={kiotPreview.employee?.matched?'preview-ok':'preview-warn'}>{kiotPreview.employee?.matched?'Đã khớp mã Kiot':'Chưa khớp mã Kiot'}</small></div><div><span>Cơ sở</span><b>{kiotPreview.branch?.name}</b><small className={kiotPreview.branch?.matched?'preview-ok':'preview-warn'}>{kiotPreview.branch?.matched?'Đã khớp cơ sở Kiot':'Chưa khớp cơ sở Kiot'}</small></div></div><div className='kiot-preview-table'><table><thead><tr><th>Ngày nghỉ</th><th>Hình thức dự kiến</th><th>Kiểm tra ca</th></tr></thead><tbody>{(kiotPreview.actions||[]).map(item=><tr key={item.work_date}><td>{date(item.work_date)}</td><td>{item.attendance_type}</td><td>{item.shift_check}</td></tr>)}</tbody></table></div>{(kiotPreview.warnings||[]).length>0&&<div className='kiot-preview-warnings'><b>Lưu ý trước khi chạy thật</b><ul>{kiotPreview.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></div>}<button type='button' className='primary full' onClick={()=>setKiotPreview(null)}>Đóng bản test</button></section></div>}
</div>
}

export function ExecutiveDashboard({profile,branches}){
 const initialRange=presetRange('this_month');
 const [period,setPeriod]=useState('this_month'),[periodOpen,setPeriodOpen]=useState(false),[branch,setBranch]=useState(''),[from,setFrom]=useState(initialRange[0]),[to,setTo]=useState(initialRange[1]),[data,setData]=useState(null),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);const range=period==='custom'?[from,to]:presetRange(period);const {data:d,error}=await supabase.rpc('get_work_report',{period_kind:'custom',target_branch:branch||null,start_on:range[0],end_on:range[1]});if(error)message(error);else setData(d);setLoading(false)}
 useEffect(()=>{load()},[profile.id,period,branch,from,to]);
 const choosePeriod=value=>{setPeriod(value);setPeriodOpen(false)};
 const departments=data?.departments||[],missingHistory=['yesterday','last_week','last_month'].includes(period)&&data?.has_history===false&&!departments.length;return <div className='ops-stack'><section className='panel executive-filter'><div><h3>Báo cáo công việc</h3><p>Tiến độ checklist theo kỳ; lịch sử được lưu gọn trong 70 ngày gần nhất.</p></div><div className='work-report-controls'><div className='period-picker'><button type='button' className='period-trigger' onClick={()=>setPeriodOpen(!periodOpen)}>{period==='custom'?'Tùy chỉnh':PERIOD_LABELS[period]}<span>⌄</span></button>{periodOpen&&<div className='period-menu'>{PERIOD_GROUPS.map(group=><div className='period-group' key={group.title}><b>{group.title}</b>{group.items.map(([value,label])=><button type='button' key={value} className={period===value?'active':''} onClick={()=>choosePeriod(value)}>{label}</button>)}</div>)}<div className='period-group'><b>Tùy chỉnh</b><button type='button' className={period==='custom'?'active':''} onClick={()=>choosePeriod('custom')}>Chọn khoảng ngày</button></div></div>}</div><select className='work-branch-filter' aria-label='Cơ sở' value={branch} onChange={e=>setBranch(e.target.value)}><option value=''>Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>{period==='custom'&&<><label>Từ ngày<input type='date' value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Đến ngày<input type='date' min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></>}<button type='button' className='work-refresh' onClick={load}>Làm mới</button></div>{missingHistory&&<div className='report-history-note'>Kỳ này chưa có dữ liệu lưu trữ. Hệ thống sẽ tự ghi nhận từ ngày bắt đầu triển khai.</div>}</section>
 {loading?<section className='panel'>Đang tổng hợp...</section>:<><section className='panel'><h3>Kết quả theo bộ phận</h3><div className='ops-chart'>{['Lễ tân','PT','Sale'].map(name=>{const x=departments.find(d=>d.department===name),pct=Number(x?.percent||0);return <div className='ops-chart-item' key={name}><strong>{x?.total?pct+'%':'—'}</strong><div className='ops-chart-track'><i style={{height:pct+'%'}}/></div><b>{name}</b><small>{x?.total?`${x.done}/${x.total} mục`:'Chưa có dữ liệu'}</small></div>})}</div></section><section className='panel'><h3>Checklist chưa hoàn thành theo chu kỳ</h3><div className='ops-summary'>{['Ngày','Tuần','Tháng'].map((x,i)=><span key={x}>{x}: <b>{data?.overdue?.[['daily','weekly','monthly'][i]]||0}</b></span>)}</div></section><section className='panel'><h3>Theo cơ sở</h3><div className='ops-table'><table><thead><tr><th>Cơ sở</th><th>Hoàn thành</th><th>Chưa hoàn thành</th></tr></thead><tbody>{(data?.branches||[]).map(x=><tr key={x.branch_id}><td>{x.branch_name}</td><td>{x.total?x.percent+'%':'—'}</td><td>{x.total-x.done}</td></tr>)}</tbody></table></div></section></>}
 </div>
}
