import React,{useEffect,useMemo,useState}from'react';
import{supabase}from'./supabaseClient';

const today=()=>new Date().toISOString().slice(0,10);
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const RESULTS=['Đã đến','Đã tập thử','Đã chốt','Chưa chốt','Không đến','Khách hủy'];
const FOLLOW_RESULTS=['Chưa chốt','Không đến','Khách hủy'];
const statusClass=s=>s==='Đã chốt'?'sold':s==='Đã tập thử'?'trial':s==='Đã đến'?'arrived':s==='Không đến'||s==='Khách hủy'?'missed':s==='Chưa cập nhật'?'follow':'pending';

export default function SalesAppointments({profile,branches,users,onLeadChanged}){
 const manager=['admin','manager'].includes(profile.role),saleUsers=users.filter(u=>u.active&&['sale','manager','admin'].includes(u.role));
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[createOpen,setCreateOpen]=useState(false),[resultRow,setResultRow]=useState(null);
 const [filter,setFilter]=useState({date:today(),branch_id:'',owner_id:'',status:''});
 const [form,setForm]=useState({phone:'',name:'',date:today(),time:'18:00',need:'Kickfit',expected_revenue:6000000,branch_id:profile.branch_id||branches[0]?.id||'',owner_id:profile.id,note:''});
 const [leadHint,setLeadHint]=useState(null),[result,setResult]=useState({status:'',package_name:'',actual_revenue:0,note:'',follow_up_date:tomorrow()});
 const branchName=id=>branches.find(b=>b.id===id)?.name||'Chưa gán cơ sở',userName=id=>users.find(u=>u.id===id)?.full_name||'Chưa gán Sale';
 async function load(){setLoading(true);await supabase.rpc('mark_stale_sales_appointments');let q=supabase.from('sales_appointments').select('id,lead_id,customer_name,phone,branch_id,owner_id,appointment_date,appointment_time,need,expected_revenue,actual_revenue,package_name,status,note,outcome_note,follow_up_date').eq('appointment_date',filter.date).order('appointment_time');if(filter.branch_id)q=q.eq('branch_id',filter.branch_id);if(filter.owner_id)q=q.eq('owner_id',filter.owner_id);if(filter.status)q=q.eq('status',filter.status);const{data,error}=await q.limit(300);setLoading(false);if(error)alert(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[filter.date,filter.branch_id,filter.owner_id,filter.status]);
 async function checkPhone(value){const phone=value.replace(/\s/g,'');setForm(f=>({...f,phone}));if(phone.length<9)return setLeadHint(null);const{data}=await supabase.from('leads').select('id,name,owner_id,branch_id,status').eq('phone',phone).order('created_at',{ascending:false}).limit(1).maybeSingle();if(data){setLeadHint({found:true,text:`Đã có Lead: ${data.name} · ${data.status}`});setForm(f=>({...f,name:data.name||f.name}))}else setLeadHint({found:false,text:'Chưa có Lead. Khi lưu, CRM sẽ tự tạo Lead mới và gán cho Sale.'})}
 async function createAppointment(e){e.preventDefault();if(busy)return;setBusy(true);const{error}=await supabase.rpc('create_sales_appointment',{customer_phone:form.phone,customer_full_name:form.name,target_branch:form.branch_id,target_owner:form.owner_id,appointment_on:form.date,appointment_at:form.time,customer_need:form.need,projected_revenue:Number(form.expected_revenue||0),appointment_note:form.note||''});setBusy(false);if(error)return alert(error.message);setCreateOpen(false);setLeadHint(null);setForm(f=>({...f,phone:'',name:'',note:'',date:filter.date,time:'18:00'}));await load();onLeadChanged?.()}
 async function saveResult(e){e.preventDefault();if(!result.status)return alert('Hãy chọn kết quả lịch hẹn');if(busy)return;setBusy(true);const{error}=await supabase.rpc('update_sales_appointment_result',{appointment_id:resultRow.id,result_status:result.status,sold_package:result.package_name||'',realized_revenue:Number(result.actual_revenue||0),result_note:result.note||'',next_follow_up:FOLLOW_RESULTS.includes(result.status)?result.follow_up_date:null});setBusy(false);if(error)return alert(error.message);setResultRow(null);await load();onLeadChanged?.()}
 function openResult(row){setResultRow(row);setResult({status:'',package_name:row.package_name||'',actual_revenue:row.expected_revenue||0,note:'',follow_up_date:tomorrow()})}
 const kpi=useMemo(()=>({total:rows.length,arrived:rows.filter(r=>['Đã đến','Đã tập thử','Đã chốt'].includes(r.status)).length,missed:rows.filter(r=>r.status==='Không đến').length,sold:rows.filter(r=>r.status==='Đã chốt').length,expected:rows.reduce((s,r)=>s+Number(r.expected_revenue||0),0),actual:rows.reduce((s,r)=>s+Number(r.actual_revenue||0),0)}),[rows]);
 return <div className='sales-appts'>
  <div className='sales-appt-head'><div><h3>Lịch hẹn khách của Sale</h3><p>Theo dõi khách đến, tập thử, chốt và doanh số theo ngày.</p></div><button className='primary' onClick={()=>{setForm(f=>({...f,date:filter.date}));setCreateOpen(true)}}>+ Đăng ký lịch hẹn</button></div>
  <div className='sales-appt-kpis'><Metric t='Tổng lịch' v={kpi.total}/><Metric t='Khách đã đến' v={kpi.arrived}/><Metric t='Không đến' v={kpi.missed} danger/><Metric t='Đã chốt' v={kpi.sold} success/><Metric t='Dự doanh số' v={money(kpi.expected)}/><Metric t='Doanh số thực tế' v={money(kpi.actual)} success/></div>
  <section className='panel sales-appt-filters'><label>Ngày xem<input type='date' value={filter.date} onChange={e=>setFilter({...filter,date:e.target.value})}/></label>{manager&&<label>Cơ sở<select value={filter.branch_id} onChange={e=>setFilter({...filter,branch_id:e.target.value,owner_id:''})}><option value=''>Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}{manager&&<label>Sale<select value={filter.owner_id} onChange={e=>setFilter({...filter,owner_id:e.target.value})}><option value=''>Tất cả Sale</option>{saleUsers.filter(u=>!filter.branch_id||u.branch_id===filter.branch_id).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label>}<label>Trạng thái<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value=''>Tất cả trạng thái</option>{['Chờ khách','Đã đến','Đã tập thử','Đã chốt','Chưa chốt','Không đến','Khách hủy','Chưa cập nhật'].map(x=><option key={x}>{x}</option>)}</select></label></section>
  <section className='panel sales-appt-table'><div className='table'><table><thead><tr><th>Giờ</th><th>Khách hàng</th><th>Nhu cầu</th><th>Cơ sở / Sale</th><th>Dự doanh số</th><th>Trạng thái</th><th>Xử lý</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td data-label='Giờ'><b className='appt-time'>{String(r.appointment_time).slice(0,5)}</b></td><td data-label='Khách hàng'><b>{r.customer_name}</b><span>{r.phone} · {r.lead_id?'Đã liên kết Lead':'Chưa có Lead'}</span></td><td data-label='Nhu cầu'>{r.need}<span>{r.note}</span></td><td data-label='Cơ sở / Sale'>{branchName(r.branch_id)}<span>{userName(r.owner_id)}</span></td><td data-label='Dự doanh số'><b>{money(r.expected_revenue)}</b>{Number(r.actual_revenue)>0&&<span>Thực tế: {money(r.actual_revenue)}</span>}</td><td data-label='Trạng thái'><i className={'appt-status '+statusClass(r.status)}>{r.status}</i></td><td data-label='Xử lý'>{r.status==='Đã chốt'?<i className='appt-status sold'>Hoàn thành</i>:<button onClick={()=>openResult(r)}>Cập nhật</button>}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan='7'>Chưa có lịch hẹn trong ngày đã chọn.</td></tr>}{loading&&<tr><td colSpan='7'>Đang tải lịch hẹn...</td></tr>}</tbody></table></div></section>
  {createOpen&&<div className='modal' onMouseDown={()=>setCreateOpen(false)}><form className='modal-card sales-appt-modal' onMouseDown={e=>e.stopPropagation()} onSubmit={createAppointment}><div className='modal-head'><h3>Đăng ký lịch hẹn</h3><button type='button' onClick={()=>setCreateOpen(false)}>×</button></div><div className='sales-appt-form'><label>Số điện thoại *<input required inputMode='tel' value={form.phone} onChange={e=>checkPhone(e.target.value)} placeholder='09xxxxxxxx'/></label><label>Tên khách hàng *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{leadHint&&<p className={'lead-hint '+(leadHint.found?'found':'new')}>{leadHint.text}</p>}<label>Ngày hẹn *<input required type='date' value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Giờ hẹn *<input required type='time' value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Nhu cầu<select value={form.need} onChange={e=>setForm({...form,need:e.target.value})}>{['Kickfit','Boxing','Gym','PT cá nhân','Giảm cân','Tăng cơ'].map(x=><option key={x}>{x}</option>)}</select></label><label>Dự doanh số *<input required type='number' min='0' step='100000' value={form.expected_revenue} onChange={e=>setForm({...form,expected_revenue:e.target.value})}/></label>{manager&&<label>Cơ sở<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value,owner_id:''})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}{manager&&<label>Sale phụ trách<select required value={form.owner_id} onChange={e=>setForm({...form,owner_id:e.target.value})}>{saleUsers.filter(u=>!form.branch_id||u.branch_id===form.branch_id||u.id===profile.id).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label>}<label className='wide'>Ghi chú<textarea rows='2' value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className='primary full' disabled={busy}>{busy?'Đang lưu...':'Lưu lịch hẹn'}</button></form></div>}
  {resultRow&&<div className='modal' onMouseDown={()=>setResultRow(null)}><form className='modal-card sales-appt-modal' onMouseDown={e=>e.stopPropagation()} onSubmit={saveResult}><div className='modal-head'><div><h3>Cập nhật kết quả</h3><p>{resultRow.customer_name} · {String(resultRow.appointment_time).slice(0,5)} · Dự {money(resultRow.expected_revenue)}</p></div><button type='button' onClick={()=>setResultRow(null)}>×</button></div><div className='result-grid'>{RESULTS.map(x=><button type='button' key={x} className={result.status===x?'active':''} onClick={()=>setResult({...result,status:x})}>{x}</button>)}</div>{result.status==='Đã chốt'&&<div className='sales-appt-form'><label>Gói đã bán *<input required value={result.package_name} onChange={e=>setResult({...result,package_name:e.target.value})}/></label><label>Doanh số thực tế *<input required type='number' min='1' step='100000' value={result.actual_revenue} onChange={e=>setResult({...result,actual_revenue:e.target.value})}/></label></div>}{FOLLOW_RESULTS.includes(result.status)&&<label>Ngày chăm sóc lại<input required type='date' value={result.follow_up_date} onChange={e=>setResult({...result,follow_up_date:e.target.value})}/></label>}<label>Ghi chú kết quả<textarea rows='3' value={result.note} onChange={e=>setResult({...result,note:e.target.value})}/></label><button className='primary full' disabled={busy}>{busy?'Đang lưu...':'Lưu kết quả'}</button></form></div>}
 </div>
}

function Metric({t,v,danger,success}){return <div className={'sales-appt-metric '+(danger?'danger ':'')+(success?'success':'')}><span>{t}</span><b>{v}</b></div>}
